### ISSUE TITLE
國際服回報無法使用

### ISSUE THREAD

**Issue by tomylee78** [biuuu/star-rail-warp-export#1]
首先感謝作者連假期間還幫大家開發鐵道抽卡小工具，真的辛苦了Orz

身為隔壁棚 [genshin-wish-export](https://github.com/biuuu/genshin-wish-export) 的忠實用戶，我算是曉得該怎麼使用此工具的

目前測試情況是國際服點選抽卡頁面，小工具都會告知找不到 URL，

測試的畫面如下，再請作者參考，

![圖片](https://user-images.githubusercontent.com/18226193/235440918-bb6b2fab-0b09-4ace-a108-b5dae48cd13b.png)

![圖片](https://i.imgur.com/8OTcqxB.png)

![圖片](https://i.imgur.com/ynbY0BN.png)

![圖片](https://i.imgur.com/ZOJak4P.png)

**Comment by biuuu** [comment]
看看是否有这个文件夹，里面有什么
C:\Users\{你的用户名}\AppData\LocalLow\Cognosphere\Star Rail\

**Comment by tomylee78** [comment]
> 看看是否有这个文件夹，里面有什么 C:\Users{你的用户名}\AppData\LocalLow\Cognosphere\Star Rail\

目前裡面有這些東西，請參考

![圖片](https://user-images.githubusercontent.com/18226193/235442113-c51f5671-5cac-4cb3-9411-5faee1424479.png)

**Comment by biuuu** [comment]
打开 
![image](https://user-images.githubusercontent.com/10892119/235442273-84146781-e6e0-4379-b37e-4928f9149580.png)
这个能看到游戏安装路径吗

**Comment by tomylee78** [comment]
> 打开 ![image](https://user-images.githubusercontent.com/10892119/235442273-84146781-e6e0-4379-b37e-4928f9149580.png) 这个能看到游戏安装路径吗

看起來應該是有正確指向安狀路徑

![圖片](https://i.imgur.com/nAXaIYR.png)

**Comment by biuuu** [comment]
用文本编辑器打开这个文件`Star Rail\Game\StarRail_Data\webCaches\Cache\Cache_Data\data_2` 。
然后查找这个关键词 `e20211215gacha-v2/index.html`，这样应该能找到一个URL，你可以去掉其中的`authkey=***`，然后发出来我看一下。

**Comment by MuLinForest** [comment]
我能提供一下:
`https://webstatic-sea.hoyoverse.com/hkrpg/event/e20211215gacha-v2/index.html?authkey_ver=1&sign_type=2&auth_appid=webview_gacha&win_mode=fullscreen&gacha_id=58d9ed53da77a3ebb1a52c311f892465c5fd&timestamp=1681910055&region=prod_official_asia&default_gacha_type=2&lang=zh-cn&authkey=xxx&game_biz=hkrpg_global&os_system=Windows%2011%20%20%2810.0.22621%29%2064bit&device_model=MS-7C94%20%28Micro-Star%20International%20Co.%2C%20Ltd.%29&plat_type=pc`

**Comment by tomylee78** [comment]
> 我能提供一下: `https://webstatic-sea.hoyoverse.com/hkrpg/event/e20211215gacha-v2/index.html?authkey_ver=1&sign_type=2&auth_appid=webview_gacha&win_mode=fullscreen&gacha_id=58d9ed53da77a3ebb1a52c311f892465c5fd&timestamp=1681910055&region=prod_official_asia&default_gacha_type=2&lang=zh-cn&authkey=xxx&game_biz=hkrpg_global&os_system=Windows%2011%20%20%2810.0.22621%29%2064bit&device_model=MS-7C94%20%28Micro-Star%20International%20Co.%2C%20Ltd.%29&plat_type=pc`

大感謝！  剛好人在外面吃飯，遠端操控不方便，你能提供真的是太好了

**Comment by qb4836** [comment]
我剛剛也是不能用 後來開啟程式裡面的proxy 就抓的到了 
這邊也幫忙回報下!

**Comment by biuuu** [comment]
没想到国际服的路径里是 Games ，多了个s

**Comment by MuLinForest** [comment]
喔喔，是的 😂
![Snipaste_2023-05-01_19-30-55](https://user-images.githubusercontent.com/5525477/235446066-fbdd6483-a7b2-499a-98a8-c2dd08996bcc.jpg)

**Comment by biuuu** [comment]
试下 0.0.6 吧

**Comment by tomylee78** [comment]
> 试下 0.0.6 吧

成功了，國際服亞洲區可以正常抓取使用

我再向台灣地區的玩家們推廣這個工具

謝謝作者！！

![Uploading Screenshot_20230501-193545012.jpg…]()

**Comment by tomylee78** [comment]
在台灣的巴哈姆特星穹鐵道專版貼文宣傳了

[文宣連結](https://forum.gamer.com.tw/C.php?bsn=72822&snA=1360&subbsn=0&page=1&gothis=14096#14096)

再次感謝 @biuuu  在那麼短的時間內提供這份抽卡紀錄工具給大家使用 💖
