### ISSUE TITLE
使用第三方启动器无法正确找到URL

### ISSUE THREAD

**Issue by shoucandanghehe** [biuuu/star-rail-warp-export#17]
使用的启动器：[Collapse](https://github.com/neon-nyan/Collapse)
没有 `C:\Users\UserName\AppData\LocalLow\Cognosphere\` 目录（？
![image](https://user-images.githubusercontent.com/51957264/236483872-c9ee6607-894b-426f-860c-6c645e23d7ed.png)
`data_2`文件内有正常的url

**Comment by shoucandanghehe** [comment]
或许加个功能让用户自己定位游戏目录

**Comment by vvb2060** [comment]
https://github.com/neon-nyan/Collapse/issues/126#issuecomment-1530754679
