### ISSUE TITLE
功能请求 星琼获取/消耗记录

### ISSUE THREAD

**Issue by vvb2060** [biuuu/star-rail-warp-export#19]
在游戏中打开手机菜单，点击问题反馈按钮，跳转到外部浏览器，在打开的网页中选择自助查询。可以查询
星琼获取/消耗记录
古老梦华获取/消耗记录
遗器获取/消耗记录（4星及以上）
光锥获取/消耗记录（4星及以上）
开拓力获取记录与消耗查询

由于这些数据也仅保存6个月，因此希望持久存储和分析统计。

**Comment by CSSQY** [comment]
支持

**Comment by qiansen1386** [comment]
反对。这样功能太臃肿了。而且操作不便，很难教会用户如何操作。

**Comment by vvb2060** [comment]
请问，如果不会从浏览器上复制网址，那macos上的用户该如何使用这款软件呢？

**Comment by biuuu** [comment]
这些数据其实挺有意思的，不过要加功能需要改动挺多的，感觉不如重写个新工具整合一下了。
这个项目代码比较乱，算是能运行就别动的感觉了。

**Comment by vvb2060** [comment]
好的，如果不介意这个issue先挂在这里不关。主要是国际服目前还没有札记和冒险记录，什么分析统计都看不到，特别难受。

**Comment by vvb2060** [comment]
https://github.com/Scighost/Starward 此项目已经支持
