### ISSUE TITLE
“群星跃迁”卡池名是否应该修改为“常驻跃迁”

### ISSUE THREAD

**Issue by cntvc** [biuuu/star-rail-warp-export#22]
**角色活动跃迁**、**常驻跃迁**均为卡池类型，**群星跃迁**为卡池名称

<img width="960" alt="1" src="https://user-images.githubusercontent.com/119989194/236815900-13c1f758-0605-4cc7-a315-03f0af7c4556.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/119989194/236815967-bf18400a-963e-4807-8848-d5764559a87a.png">
<img width="545" alt="2" src="https://user-images.githubusercontent.com/119989194/236816700-539737ab-4e92-4216-ad48-038028e8da33.png">

**Comment by cntvc** [comment]
另外想问下大佬是怎么实现 i18n 的准确翻译呢，想要靠机翻似乎不太准确，特别是卡池名这种在游戏中有官方名称的

https://github.com/biuuu/star-rail-warp-export/blob/1052a4bffb67098c4e623209b760336b4abc5a4a/src/main/getData.js#L266

**Comment by qiansen1386** [comment]
切过去看不就行了

**Comment by cntvc** [comment]
> 切过去看不就行了

抱歉，是我问题没描述完整。之前也试过游戏内切换语言，确实可以看到翻译，但是怎么把这个文本弄到代码里面呢，中文英文这种语言还可以自己输入法打出来，日文韩文这种没想到什么简单方法。

**Comment by TremblingMoeNew** [comment]
> > 切过去看不就行了
> 
> 抱歉，是我问题没描述完整。之前也试过游戏内切换语言，确实可以看到翻译，但是怎么把这个文本弄到代码里面呢，中文英文这种语言还可以自己输入法打出来，日文韩文这种没想到什么简单方法。

有个项目叫StarRailData，是解包（

**Comment by cntvc** [comment]
> 有个项目叫StarRailData，是解包（

找到相关文本了，感谢大佬指路

**Comment by biuuu** [comment]
https://webstatic.mihoyo.com/admin/mi18n/hkrpg_cn/m12211711281351/m12211711281351-zh-cn.json
我是取的这里的文本。
改成常驻跃迁更明了，不过群星跃迁比较 cool 。
确实要改可以发个 PR，但所有语言都需要改下。
