### ISSUE TITLE
如果其中一個池沒有抽卡紀錄會遇到作業失敗

### ISSUE THREAD

**Issue by yoruneko-digitalmedia** [biuuu/star-rail-warp-export#26]
![image](https://github.com/biuuu/star-rail-warp-export/assets/131511538/6900b819-5156-4743-9e7a-0c923d54d595)

我想說要留給符玄所以希兒池一抽未動，結果就...

**Comment by biuuu** [comment]
可能是自动更新有问题，你下载个完整的试试

**Comment by yoruneko-digitalmedia** [comment]
重新下載[v0.0.16]問題依舊存在 以下是我開發模式下的報錯
![image](https://github.com/biuuu/star-rail-warp-export/assets/131511538/53e30ae0-22bc-4ed4-b3a3-41f48b096696)

**Comment by yoruneko-digitalmedia** [comment]
我把躍遷頁面關掉回到遊戲問題就解決了
