### ISSUE TITLE
限定池抽卡数据获取不完整

### ISSUE THREAD

**Issue by qingchiang** [biuuu/star-rail-warp-export#28]
系统: Windows 11

详情:
游戏里查看限定池记录总计16页80抽，但是工具只获取到了40抽
（5月7-8号40抽，10号40抽，导出excel记录只有5月10号的记录）
但是常驻池跟新手池数据完整，没有错误（包括10号之前的数据）

其他信息:
没有抽过光锥池
亚服，工具里日志类型设置过自动/外服，结果一样
设置里启用了“获取完整数据”，结果一样

**Comment by biuuu** [comment]
https://github.com/orgs/UIGF-org/discussions/7
从这里随便找个其他工具试试，看是否有相同的问题

**Comment by qingchiang** [comment]
> https://github.com/orgs/UIGF-org/discussions/7 从这里随便找个其他工具试试，看是否有相同的问题

谢谢回复~
刚刚试了试下面两个
BoxCatTeam/SRCat : 照说明设置游戏路径之后，游戏里打开历史记录，软件里点击获取数据，无任何提示，但是获取失败
vikiboss/star-rail-gacha-export : 游戏路径没问题，游戏里打开历史记录，软件里点击更新数据，提示"未找到API地址"，获取失败

**Comment by biuuu** [comment]
可能这两个不支持国际服，这个好像可以https://github.com/cntvc/star-rail-tools

**Comment by qingchiang** [comment]
> 可能这两个不支持国际服，这个好像可以https://github.com/cntvc/star-rail-tools

刚刚试过了，这个工具给出的数据是对的:
+-----------------------------------------------------------------+
|                             统计结果                            |
+-------------+----------+----------+--------------+--------------+
|     项目    | 常驻跃迁 | 新手跃迁 | 角色活动跃迁 | 光锥活动跃迁 |
+-------------+----------+----------+--------------+--------------+
|   抽卡总数  |    81    |    50    |      80      |      10      |
|  5星总次数  |    0     |    1     |      1       |      0       |
| 5星平均抽数 |    -     |   50.0   |     78.0     |      -       |
|  保底内抽数 |    0     |    0     |      2       |      0       |
+-------------+----------+----------+--------------+--------------+

为了测试我还抽了10抽光锥，你的工具也能统计出来
只有角色限定池数据不太对

**Comment by biuuu** [comment]
我自己的账号无法复现，
能否帮忙提供下你的抽卡页面URL进行测试。
URL获取方法是：
用文本编辑器打开  `游戏文件夹/Games/StarRail_Data/webCaches/Cache/Cache_Data/data_2`
搜索 `https://` 的文本，找到其中打开后可以正常查看历史记录的网址。

你可以把 URL 发到我邮箱：luna@css.moe

**Comment by qingchiang** [comment]
> 我自己的账号无法复现， 能否帮忙提供下你的抽卡页面URL进行测试。 URL获取方法是： 用文本编辑器打开 `游戏文件夹/Games/StarRail_Data/webCaches/Cache/Cache_Data/data_2` 搜索 `https://` 的文本，找到其中打开后可以正常查看历史记录的网址。
> 
> 你可以把 URL 发到我邮箱：[luna@css.moe](mailto:luna@css.moe)
我按照代码里的流程，每页20个手动获取了限定池的抽卡记录（4页80个，看上去是完整的）
记录发到你的邮箱了
邮件名: StarRailWarpExport工具的“限定池抽卡数据获取不完整”issue相关

**Comment by biuuu** [comment]
只有返回结果看不出问题，
你可以观察下在启用获取全部数据后，点更新数据时按钮下面显示限定池获取到了几页数据。
也可以把userData里的json发我看看。

**Comment by qingchiang** [comment]
> 

邮件已发，请查收
软件界面上角色限定卡池的最大页数只跳到了3，最后记录里只有2页40条记录
但是我指定"page=3,size=20,end_id=第2页最后一项的id"能够拿到数据

**Comment by biuuu** [comment]
找不到原因啊，除非直接用出现问题的URL进行调试

**Comment by qingchiang** [comment]
> 找不到原因啊，除非直接用出现问题的URL进行调试

我周末有空了弄个js的环境试试看吧~谢谢啦

**Comment by biuuu** [comment]
尝试修了下，不知道是不是这个问题。
如果有效果的话可能会在40抽后中断，然后等5秒重试

**Comment by qingchiang** [comment]
> 尝试修了下，不知道是不是这个问题。 如果有效果的话可能会在40抽后中断，然后等5秒重试

不好意思，这几天出了点状况住院去了……
刚刚测试了一下，在获取限定池第3页的时候会失败一次，之后等5秒重试的时候就能正常获取了
现在全部抽卡数据都是正确的，谢谢啦！
