### ISSUE TITLE
打开程序为白屏，关闭窗口后台并没有关闭

### ISSUE THREAD

**Issue by WAXBLIL** [biuuu/star-rail-warp-export#36]
设备为win11， 打开软件白屏，打开游戏软件依旧白屏，尝试过0.1.0和0.0.18都为白屏，原神的一直在用没有任何问题。试过nga上的解决办法（关闭smartscreen），并没有任何帮助，望解决！非常感谢！

**Comment by MoonCocoon** [comment]
同样问题，升级Win11 22H2后出现，后发现是因为中文文件夹，挪到非中文文件夹就好了
