### ISSUE TITLE
v0.1.5 更新資料後 不顯示item 僅顯示抽取數

### ISSUE THREAD

**Issue by ToooAir** [biuuu/star-rail-warp-export#53]
如圖所示
![empty](https://i.imgur.com/lXQXnAr.jpg)
更新資料後會顯示空白

- 確認躍遷URL是正常的(在瀏覽器可正常開啟)
- 刪除userData裡的json後重啟狀況依舊
- 取得完整資料開啟後還是一樣
- 刪除"Star Rail\Games\StarRail_Data\webCaches\Cache\Cache_Data"無效果

#52 可能跟此issue有相關關係
有需要可以提供新的URL

**Comment by ToooAir** [comment]
找到問題了
我這邊的躍遷URL為
```https://gs.hoyoverse.com/hkrpg/event/e20211215gacha-v2/index.html```
跟判斷為海外的判斷式
https://github.com/biuuu/star-rail-warp-export/blob/8c370ff0a791670f76775c628f7b00e38f58b8e8/src/main/getData.js#L293C107-L293C107
沒有相符合的選項
導致一直使用到```https://api-takumi.mihoyo.com``` 有200但不會返回任何object
使用```https://api-os-takumi.mihoyo.com```之後則正常返回20個有帶值的object

**Comment by biuuu** [comment]
原来是这样，改成判断url里是否有hoyoverse.com会不会更好些

**Comment by biuuu** [comment]
使用新版工具后“取得完整資料”能否覆盖空数据

**Comment by ToooAir** [comment]
> 原来是这样，改成判断url里是否有hoyoverse.com会不会更好些

我不太確定陸服那邊會不會使用到```hoyoverse.com```這個domain
以至於接到海外API導致工具失效之類的問題

> 使用新版工具后“取得完整資料”能否覆盖空数据

可以的 修正過後直接取得完整資料 能把之前空數據完全補上

**Comment by ToooAir** [comment]
@biuuu 
> 原来是这样，改成判断url里是否有hoyoverse.com会不会更好些

我不太確定陸服那邊會不會使用到```hoyoverse.com```這個domain
以至於接到海外API導致工具失效之類的問題

> 使用新版工具后“取得完整資料”能否覆盖空数据

可以的 修正過後直接取得完整資料 能把之前空數據完全補上
