### ISSUE TITLE
身份认证已过期，请重新打开游戏抽卡记录 - 操作失败

### ISSUE THREAD

**Issue by dalaoshi777** [biuuu/star-rail-warp-export#63]
![image](https://github.com/biuuu/star-rail-warp-export/assets/47414347/b30d0772-67b0-4cdf-a099-d380a784e868)
按照此操作处理，均无效，尝试多次

**Comment by biuuu** [comment]
设置指定日志类型试试

**Comment by dalaoshi777** [comment]
> 设置指定日志类型试试

从国服改成自动可以了，好神奇
