### ISSUE TITLE
未找到URL，请确认是否已打开游戏抽卡记录 - 操作失败

### ISSUE THREAD

**Issue by forchannot** [biuuu/star-rail-warp-export#7]
尝试过以管理员身份启动了，无论开不开代理都不行，不开代理就找不到url，开了代理进不去抽卡记录界面，然后软件一直在转圈

**Comment by biuuu** [comment]
https://github.com/biuuu/star-rail-warp-export/issues/1#issuecomment-1529579841
参考这儿的回复，看能不能找到URL提供出来看是啥问题

**Comment by forchannot** [comment]
```
https://webstatic.mihoyo.com/hkrpg/event/e20211215gacha-v2/index.html?authkey_ver=1&sign_type=2&auth_appid=webview_gacha&win_mode=fullscreen&gacha_id=dbebc8d9fbb0d4ffa067423482ce505bc5ea&timestamp=1681910012&region=prod_gf_cn&default_gacha_type=11&lang=zh-cn&authkey=xxx&game_biz=hkrpg_cn&os_system=Windows%2011%20%20%2810.0.22621%29%2064bit&device_model=HP%20Pavilion%20Gaming%20Laptop%2016-a0xxx%20%28HP%29&plat_type=pc
```

**Comment by biuuu** [comment]
包含data_2的完整游戏安装路径是啥样的

**Comment by forchannot** [comment]
"F:\Star Rail\Game\StarRail_Data\webCaches\Cache\Cache_Data\data_2"

**Comment by biuuu** [comment]
看看有没这个文件：`C:\Users\用户名\AppData\LocalLow\miHoYo\崩坏：星穹铁道\Player-prev.log`
第一行是什么内容

**Comment by forchannot** [comment]
`Loading player data from F:/star rail/game/starrail_Data/data.unity3d`

**Comment by biuuu** [comment]
原来如此，竟然是小写的，太怪了

**Comment by biuuu** [comment]
你看这个文件后面是不是也全是这样小写字母的路径，有没有跟实际安装路径完全符合的

**Comment by forchannot** [comment]
![image](https://user-images.githubusercontent.com/100580891/236104815-8e1d9ecf-13b1-4e96-8460-034ca780e70d.png)
似乎是没有的

**Comment by biuuu** [comment]
同个目录下的 Player.log 里面也是这样的吗

**Comment by forchannot** [comment]
是的

**Comment by biuuu** [comment]
不过windows好像不区分大小写，我改下试试吧

**Comment by forchannot** [comment]
更新到0.0.10后问题解决了，感谢
