### ISSUE TITLE
2.5飞霄的识别好像有问题

### ISSUE THREAD

**Issue by FujishiroOtone** [biuuu/star-rail-warp-export#79]
我其实已经抽到了，这甚至显示97抽没出了
![image](https://github.com/user-attachments/assets/907f2413-ce84-44a4-bc3a-38699dc4fcaa)

**Comment by biuuu** [comment]
userData 目录下的 json 发一份到我邮箱看看 raindrop@css.moe

**Comment by biuuu** [comment]
工具的版本是多少啊

**Comment by FujishiroOtone** [comment]
> 工具的版本是多少啊

v0.1.10，邮件发了

**Comment by biuuu** [comment]
你点选项下拉框里的复制URL，然后把URL也发一份到我邮箱吧。
我没抽卡不好测试，只好用你的看看。

**Comment by FujishiroOtone** [comment]
https://public-operation-hkrpg.mihoyo.com/common/gacha_record/api/getGachaLog?authkey_ver=1&sign_type=2&auth_appid=webview_gacha&win_mode=fullscreen&gacha_id=921189bdf80a393521799c7bcb31dbc264d5d34e&timestamp=1725925868&region=prod_gf_cn&default_gacha_type=11&lang=zh-cn&authkey=UxGSjPMc1kzhrxt87VqQM%2B8FS5zgf3FBeLbKlVm8QcZbSNWlQBa36qk0pKihBD2MMzwLO5u6kmupqI%2BNeS6IYEE%2FZDCgQV49he8ORVSAtSmEowdD266rNJZsJJFoHJw8l5ftMAs5VfjX4k6vucQxYgb2fW4ZNTVmvcl5POvkCZs8UuzwBiQtiWpuYkKStxqfLeLPCpwMY5WtRwFoPYE4lmKczFZCXuUZK%2FxzKKKhjZ03AqsfY6MvvHmOc9rt2CoUhc3VAfY%2FBxTW0qcFKghSK9Bqo0qsv2xmSNJFTZcV0wsDmeKt55EqXrZ4TmMljQMeaDjDauEWhzq3TK4ZI6RB0Y1Qyjh2G%2F%2BGlpwxDcJJ4IdxXCVtLQ9YZbhHDTBxNTyI1sBg%2FWPzRbo%2BIyQFgQXYd1Xqt35qPHw4nL8KdHmXDj7twXXC9yVewRlqH1R%2FPKqVOFnmtOJyyCh2NpXMQwpYIl7HxuAjILFAR%2FD5s%2FYNF%2FvDqCWWGwek%2BLVpq7AVfIygJJ6SpA6a2IlZHrbCdpNgl%2FBaV%2B3p4BoiMW90cMmLEgYlJvjgxAOKPBn82%2BGs7tyJH3EZnQ6RGhw%2Bbvg9v6sGVI6la7tx5YTCJ%2Fa9Po%2B%2BXGuutGAZWTe9otYIwCD8AAO8FijA6cDq2Z2NUP3IVP1BChkgY0chzXQ0VIjIFqM77fg%3D&game_biz=hkrpg_cn&os_system=Windows%2010%20%20%2810.0.19045%29%2064bit&device_model=System%20Product%20Name%20%28ASUS%29&plat_type=pc
________________________________
发件人: biuuu ***@***.***>
发送时间: 2024年9月15日 18:53
收件人: biuuu/star-rail-warp-export ***@***.***>
抄送: Otone ***@***.***>; Author ***@***.***>
主题: Re: [biuuu/star-rail-warp-export] 2.5飞霄的识别好像有问题 (Issue #79)


你点选项下拉框里的复制URL，然后把URL也发一份到我邮箱吧。
我没抽卡不好测试，只好用你的看看。

―

**Comment by FujishiroOtone** [comment]
我看到你另一条issue的留言，然后我用获取完整数据之后正常显示了，这个问题是随机性的吗？还是以后要固定获取完整数据

**Comment by biuuu** [comment]
可能是米哈游的接口问题，刚出新角色时抽卡记录里给的数据出错了
